### PR TITLE
Spring 24 Officers Update

### PR DESCRIPTION
**Pull request by chiranthans23**
add deia officers, mohsena's nn interview

image
image

### CODE REVIEW

**Review by hunhoffe — APPROVED** [review]
LGTM!

**Comment by hunhoffe** [comment]
Great job on these changes @chiranthans23 

I updated the picture for the main page, but I haven't checked if that requires format changes. Can you double check me, and then I think we're good to merge?

**Comment by chiranthans23** [comment]
@hunhoffe . Added the grad parent resources and reformated the group picture. 

image
image
image

**Review by hunhoffe — APPROVED** [review]
Looks great, thank you very much for putting this together!

**Comment by hunhoffe** [comment]
To confirm - the Graduate Student Parent Resources will appear as an option in the drop down menu for "Resource and FAQ", yes?

**Comment by chiranthans23** [comment]
Yes, @hunhoffe . If that's needed as a menu option at the top for now, I can do that too. But I think having it as a dropdown under the "Resources and FAQ" should be good

**Comment by hunhoffe** [comment]
I think the drop down is great! Thanks much!

**Pull request merged**
