### PR TITLE
Add friendsgiving photo album, reorganize posts/newsletters

### PR DESCRIPTION
**Pull request by crmauceri**
## Description
I wanted to add the photo albums to the archive page and separate old newsletters that were mixed into the posts list.

## What I did
- Add dates to carousel data
- Move some files to different directories (_posts/ to _newsletters)
- Add limit to carousel so it only shows 4 most recent photo albums
- Change front page to show newsletters not posts in newsletter section

## Unsolved problem
The newsletters aren't sorted by date

### CODE REVIEW

**Comment by casassg** [comment]
What's the reason behind moving all posts to newsletters?

**Comment by crmauceri** [comment]
I wanted to separate out posts that were ephemeral (event invites, newsletters, etc) from posts that will remain interesting to readers over time (FAQs, quality of life survey). Since the archive page already had two categories, blog posts and newsletters. I decided that newsletters are the ephemeral ones and blog posts are the more static ones. Then I took all the old event announcements and moved them to newsletters.

Since this is all in the archive anyway, this is not an important change, and we can scrap it if you think the old way was better. 

The reason I asked for a review is that I wanted you to check is why the newsletters are not listed chronologically. I thought this was a default if the collection had dates attached to posts.

**Comment by crmauceri** [comment]
The ones that I moved to newsletters were originally distributed as emails. We just didn't have a newsletter at the time.

**Comment by crmauceri** [comment]
I just noticed that the newsletter date ordering is a problem on the website right now without moving any posts around. I've opened a separate issue. #24

**Comment by casassg** [comment]
@crmauceri I think the ordering is done alphabetically. Therefore if the date is `2018-4-` even though it's recognized as April, it ordered using alphabetical order. I would need to check, but this is my theory. Renaming to `2018-04` should fix it.

**Pull request merged**
